### ISSUE TITLE
PHP 8 Tests

### ISSUE THREAD

**Issue by ancarda** [ancarda/psr7-string-stream#2]
The only production dependency (`require`) is `psr/http-message`, which already supports PHP 8.

However, some development dependencies (`require-dev`) don't support PHP 7.1 and PHP 8 at the same time. For instance, the earliest version of `phpunit/phpunit` to support PHP 8 is 9.3.0, which requires `php: ^7.3 || ^8.0`. This means, in effect, this project is going to have to either:

* Don't run tests on PHP 7.1 and 7.2 OR on PHP 8.0 (not good).
* Drop support for PHP 7.1 and 7.2 in order to be able to get support for PHP 8.0.

## My Dependencies

| Dependency                      | First version compatible with PHP 8 | Require string   |
|---------------------------------|-------------------------------------|------------------|
| php-coveralls/php-coveralls     | 1.0.2                               | ^5.3.3 \|\| ^7.0 |
| guzzlehttp/psr7                 |                                     | >=5.4.0          |
| squizlabs/php_codesniffer       | 3.5.6                               | >=5.4.0          |
| php-http/psr7-integration-tests | 1.0.0                               | ^5.5 \|\| ^7.0   |
| nyholm/psr7                     | 1.3.1                               | >=7.1            |
| phpstan/phpstan                 | 0.12.33                             | ^7.1 \| ^8.0     |
| phpstan/phpstan-phpunit         | 0.12.13                             | ^7.1 \|\| ^8.0   |
| phpstan/phpstan-strict-rules    | 0.12.4                              | ^7.1 \|\| ^8.0   |
| phpunit/phpunit                 | 9.3.0                               | ^7.3 \|\| ^8.0   |
| infection/infection             | 0.18.2     | ^7.3 \|\| ^8.0  |

Possible workaround could be to remove that dependency before running `composer install` when running PHP 8 in Travis-CI.

## Those Who Depend On Me

| Dependent                                            | Require string |
|------------------------------------------------------|----------------|
| MammatusPHP/healthz-vhost                            | ^7.4           |
| MammatusPHP/http-server-websockets                   | ^7.4           |
| reactphp-parallel/psr-15-adapter                     | ^7.4           |
| WyriHaximus/php-json-psr7                            | ^7.4           |
| WyriHaximus/ReactBlogSeriesExamples                  | ?              |
| WyriHaximus/reactphp-http-middleware-webroot-preload | ^7.4           |

**Comment by sanmai** [comment]
`infection/infection` should support PHP 8 fully FWIW.

**Comment by ancarda** [comment]
This was completed some time ago: https://builds.sr.ht/~ancarda/psr7-string-stream
